version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: pdf_storage
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/app
      - ./pdfs:/pdfs  # Mount PDFs directory
    depends_on:
      - db
    environment:
      - POSTGRES_DB=pdf_storage
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=${DEBUG:-false}
    ports:
      - "5000:5000"

volumes:
  postgres_data:
